### ISSUE TITLE
Read projections

### ISSUE THREAD

**Issue by dohnala** [Product-Foundry/akka-cqrs#16] opened 2015-12-04 14:02 UTC
Hello,

currently, I want to provide read projections to my domain. In which way I should implement this? Should I use 1) **DomainAggregator** which is considered as deprecated and if so, can you please post some working code snippet how it works? Or should I use 2) **Persistence query** module. I am currently using MongoDB journal plugin which currently does not support live event streams, so I don't know how to implement projections using persistence query. What approach do you currently use in your application? Thanks

**Comment by dohnala** [comment] 2015-12-04 19:45
After I studied  **DomainAggregator** I thing it will be sufficient to use it currently. Can you help me please with wiring with all this together (DomainAggregator, DomainAggregatorView, DomainAggregatorView)?

I understand, that **DomainAggregatorCommitter** should be mixed in to **Aggregate** ... but when? When defining aggregate or when instantiating it in **AggregateFactory#props**?

Next, **DomainAggregatorCommitter** needs reference to **DomainAggregator**, so another question is, where DomainAggregator should be created, because it needs persistenceId of Aggregate. Similar question is about **DomainAggregatorView** ... where should it be created and persistenceId should be passed in?

Some code snippet or test would be very helpful, thank you very much

**Comment by andrekampert** [comment] 2015-12-07 08:40
Personally, I would stay away from using the `DomainAggregator` class. I wanted to recover all events in a journal independant manner. On the Akka mailing list, I have read about the idea of duplicating all persisted events in a single persistent actor in order to recover using `PersistentView`. This was a quick and eady solution to allow me to rebuild my projection model on restart. There are a few problems with this approach however.

- Persisted events can get lost between an aggregate and the aggregator, meaning projected state will always be out of sync
- All events are stored twice, wasting precious space
- Current setup does not work in a clustered environment. A `ClusterSingleton` needs to be used to ensure the `DomainAggregator` is only updated on a single node
- Less usefull when persisting your projections. I tried keeping them in memory for a while because I believed this allowed me to develop quickly, but actually it slowed me down because I spent time worrying about the wrong things
- PersistentView is now deprecated. Although the query can be simulated using PersistenceQuery. One drawback I found is that very few journal plugins support PersistenceQuery yet

To anwer your question, you can mixin the trait directly in the actor. However, by doing so, you're mixing aggregate concerns with the overall need to recover, which is more an aspect of the system under development. I prefer to mixin the `DomainCommitter` trait in the `AggregateFactory`

On our projects, I prefer to publish events, so that projections can pick them up and update their persisted state. You can do this in-process or using a message broker. This way, there is less need to recover the complete state all the time. For that scenario, I am simply quering the journal storage directly. All dependencies are already in the project and I found that simply quering directly and using Akka serialization to recover all persisted events is much easier than trying to do this in a journal independent way.

Note that this library is still under heavy development. API changes are likely as I am learning better ways to do things. We are using this library ourselves in multiple projects, but then again. I hope to reach stability in the API somewhere mid 2016. There are a lot of interesting implementations for doing DDD with Akka (some in the README.md), which are worth checking out and learning from.

**Comment by dohnala** [comment] 2015-12-07 09:19
Thanks for your response. I was reading through persistence query documentation at the weekend and I would like to play with it a little. My idea is to have one actor which will first query all persistenceIds and for each persistenceId it queries all events and it will send them to specific aggregateView actor. Read journal I am using at the moment doesn't support live stream version of these queries yet, so I would implement some kind of polling myself. Also I would need to add one persistent actor to store some kind of Map[PersistenceId, LastEvetNr] to be able to process only new events at startup or when polling. 

AggregateView will handle events and construct/update view state and persist it to read database. After some time of inactivity it should be stopped. When new events arrives it should be of course started.

What do you thing about this approach? Do you see any drawbacks? Thanks

**Comment by andrekampert** [comment] 2016-09-16 10:03
Closing this as Aggregate Views shoudn't be used. Currently, we use another durable event stream where all events are duplicated. They are reliably published to this stream using ReliableDelivery and are only confirmed when written to this stream. You can think of Couchbase or Kafka to make this work, which can then be used for full recovery without the need to do any magic in the aggregate.

**Closed by andrekampert** 2016-09-16 10:03 UTC
